### ISSUE TITLE
就想问一下有人成功了吗？

### ISSUE THREAD

**Issue by chinazhen** [yeetor/AndroidControl#22]
Exception in thread "main" org.usb4java.LoaderException: Native library not found in classpath: /org/usb4java/osx-x86_64/libusb4java.dylib
	at org.usb4java.Loader.extractLibrary(Loader.java:281)
	at org.usb4java.Loader.load(Loader.java:358)
	at org.usb4java.javax.Services.<init>(Services.java:59)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at javax.usb.UsbHostManager.createUsbServices(Unknown Source)
	at javax.usb.UsbHostManager.getUsbServices(Unknown Source)
	at com.yeetor.adb.AdbServer.listenUSB(AdbServer.java:75)
	at com.yeetor.Main.main(Main.java:51)

跑这代码让我觉得我感觉我是个白痴

**Comment by weithink** [comment]
我也遇到这样的问题，master分支跑不起来，另外一个分支代码有缺少的
