### ISSUE TITLE
好奇怪连不上

### ISSUE THREAD

**Issue by mlick** [yeetor/AndroidControl#6]
```
devices://{}
takeScreenShot:LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 500x900@500x900/0 -n minicap -s -b
flush
takeScreenShot:LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1080x1920@1080x1920/0 -n minicap -s -b
flush
takeScreenShot:LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1080x1920@1080x1920/0 -n minicap -s -b
flush
wait://{"sn":"CJL7N15C16007706","key":""}
start://{"type":"minicap","config":{"rotate":90}}
start://{"type":"minitouch"}
PID: 32313
INFO: Using projection 1080x1920@324x576/1

INFO: (external/test/jni/minicap-shared/aosp/src/minicap_24.cpp:243) Creating SurfaceComposerClient
INFO: (external/test/jni/minicap-shared/aosp/src/minicap_24.cpp:246) Performing SurfaceComposerClient init check
INFO: (external/test/jni/minicap-shared/aosp/src/minicap_24.cpp:253) Creating virtual display
INFO: (external/test/jni/minicap-shared/aosp/src/minicap_24.cpp:259) Creating buffer queue
INFO: (external/test/jni/minicap-shared/aosp/src/minicap_24.cpp:264) Creating CPU consumer
INFO: (external/test/jni/minicap-shared/aosp/src/minicap_24.cpp:268) Creating frame waiter
INFO: (external/test/jni/minicap-shared/aosp/src/minicap_24.cpp:272) Publishing virtual display

Exception in thread "Thread-4" java.lang.ArrayIndexOutOfBoundsException: 0
        at com.yeetor.minicap.Minicap$ImageParser.readData(Minicap.java:518)
        at com.yeetor.minicap.Minicap$ImageParser.run(Minicap.java:488)
        at java.lang.Thread.run(Thread.java:745)
/data/local/tmp/minitouch -n CJL7N15C16007506_touch_2
Note: device /dev/input/mouse0 is not supported by libevdev

Note: device /dev/input/mice is not supported by libevdev

Type A touch device huawei,touchscreen (1079x1919 with 16 contacts) detected on /dev/input/event5 (score 1000)
Note: hard-limiting maximum number of contacts to 10
Connection established
```

**Comment by yeetor** [comment]
判断错误需要更多的信息。麻烦加一下qq群1476686。
